services:
  - type: pserv
    name: avat-database
    env: postgres
    databaseName: avat_prod
    ipAllowList: []  # Only accessible by other services in this project

  - type: redis
    name: avat-redis
    ipAllowList: []  # Only accessible by other services in this project

  - type: web
    name: avat-backend
    env: python
    plan: free
    buildCommand: |
      # Install system dependencies for PDF processing
      # These should be available on Render's runtime
      echo "Checking for required system packages..."

      # Install Python dependencies using Poetry
      poetry install --no-dev --no-interaction --no-ansi

      # --- Frontend build (unchanged) ---
      cd frontend
      export NODE_ENV=production
      npm install -g pnpm@8.15.8
      pnpm install --no-frozen-lockfile
      pnpm run build

      cd ..
      mkdir -p static
      cp -r frontend/build/* static/
      touch static/build-complete.flag
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: AVAT_DATA_DIR
        value: /opt/render/project/.data/pdfs
      - key: TZ
        value: UTC

      # ✅ Force a Python with wheels available for NumPy/SciPy
      - key: PYTHON_VERSION
        value: 3.11.9

      # ✅ Enforce wheel-only installs at runtime too (defense-in-depth)
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: avat-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: avat-redis
          property: connectionString
    healthCheckPath: /api/v1/health

