/**
 * Mock data service for production deployment
 * Provides fallback data when backend API is not available
 */

import { AccidentRecord } from '../types';

export const mockAccidents: AccidentRecord[] = [
  {
    id: 1,
    timestamp: '2023-12-15T14:30:00Z',
    company: 'Waymo',
    vehicle_make: 'Chrysler',
    vehicle_model: 'Pacifica',
    location_address: '1600 Amphitheatre Pkwy, Mountain View, CA',
    location_lat: 37.4220,
    location_lng: -122.0841,
    city: 'Mountain View',
    county: 'Santa Clara',
    city_type: 'suburban',
    intersection_type: 'traffic light',
    damage_severity: 'minor',
    weather_conditions: 'clear',
    time_of_day: '14:30',
    casualties: 0,
    av_mode: 'autonomous',
    speed_limit: 35,
    traffic_signals: 'functioning',
    road_type: 'arterial',
    damage_location: 'front',
    raw_text: 'Waymo vehicle collision at traffic light intersection',
    report_url: 'https://dmv.ca.gov/report/1',
    created_at: '2023-12-15T14:35:00Z'
  },
  {
    id: 2,
    timestamp: '2023-12-14T09:15:00Z',
    company: 'Cruise',
    vehicle_make: 'Chevrolet',
    vehicle_model: 'Bolt',
    location_address: '101 California St, San Francisco, CA',
    location_lat: 37.7929,
    location_lng: -122.3963,
    city: 'San Francisco',
    county: 'San Francisco',
    city_type: 'urban',
    intersection_type: 'stop sign',
    damage_severity: 'moderate',
    weather_conditions: 'fog',
    time_of_day: '09:15',
    casualties: 1,
    av_mode: 'autonomous',
    speed_limit: 25,
    traffic_signals: 'none',
    road_type: 'residential',
    damage_location: 'side',
    raw_text: 'Cruise vehicle accident at stop sign intersection',
    report_url: 'https://dmv.ca.gov/report/2',
    created_at: '2023-12-14T09:20:00Z'
  },
  {
    id: 3,
    timestamp: '2023-12-13T16:45:00Z',
    company: 'Tesla',
    vehicle_make: 'Tesla',
    vehicle_model: 'Model 3',
    location_address: '1 Hacker Way, Menlo Park, CA',
    location_lat: 37.4847,
    location_lng: -122.1477,
    city: 'Menlo Park',
    county: 'San Mateo',
    city_type: 'suburban',
    intersection_type: 'roundabout',
    damage_severity: 'severe',
    weather_conditions: 'rain',
    time_of_day: '16:45',
    casualties: 2,
    av_mode: 'disengaged',
    speed_limit: 30,
    traffic_signals: 'none',
    road_type: 'arterial',
    damage_location: 'multiple',
    raw_text: 'Tesla autopilot disengagement before collision',
    report_url: 'https://dmv.ca.gov/report/3',
    created_at: '2023-12-13T16:50:00Z'
  },
  {
    id: 4,
    timestamp: '2023-12-12T11:20:00Z',
    company: 'Waymo',
    vehicle_make: 'Chrysler',
    vehicle_model: 'Pacifica',
    location_address: '2000 University Ave, Palo Alto, CA',
    location_lat: 37.4419,
    location_lng: -122.1430,
    city: 'Palo Alto',
    county: 'Santa Clara',
    city_type: 'suburban',
    intersection_type: 'traffic light',
    damage_severity: 'minor',
    weather_conditions: 'clear',
    time_of_day: '11:20',
    casualties: 0,
    av_mode: 'autonomous',
    speed_limit: 35,
    traffic_signals: 'functioning',
    road_type: 'arterial',
    damage_location: 'rear',
    raw_text: 'Minor rear-end collision during traffic light stop',
    report_url: 'https://dmv.ca.gov/report/4',
    created_at: '2023-12-12T11:25:00Z'
  },
  {
    id: 5,
    timestamp: '2023-12-11T18:30:00Z',
    company: 'Cruise',
    vehicle_make: 'Chevrolet',
    vehicle_model: 'Bolt',
    location_address: '555 Mission St, San Francisco, CA',
    location_lat: 37.7886,
    location_lng: -122.3972,
    city: 'San Francisco',
    county: 'San Francisco',
    city_type: 'urban',
    intersection_type: 'intersection',
    damage_severity: 'moderate',
    weather_conditions: 'clear',
    time_of_day: '18:30',
    casualties: 0,
    av_mode: 'autonomous',
    speed_limit: 30,
    traffic_signals: 'functioning',
    road_type: 'arterial',
    damage_location: 'front',
    raw_text: 'Intersection collision during rush hour',
    report_url: 'https://dmv.ca.gov/report/5',
    created_at: '2023-12-11T18:35:00Z'
  },
  {
    id: 6,
    timestamp: '2023-12-10T08:45:00Z',
    company: 'Tesla',
    vehicle_make: 'Tesla',
    vehicle_model: 'Model Y',
    location_address: '1 Tesla Rd, Fremont, CA',
    location_lat: 37.5483,
    location_lng: -121.9886,
    city: 'Fremont',
    county: 'Alameda',
    city_type: 'suburban',
    intersection_type: 'stop sign',
    damage_severity: 'minor',
    weather_conditions: 'clear',
    time_of_day: '08:45',
    casualties: 0,
    av_mode: 'autonomous',
    speed_limit: 25,
    traffic_signals: 'none',
    road_type: 'residential',
    damage_location: 'side',
    raw_text: 'Side impact at stop sign intersection',
    report_url: 'https://dmv.ca.gov/report/6',
    created_at: '2023-12-10T08:50:00Z'
  },
  {
    id: 7,
    timestamp: '2023-12-09T15:15:00Z',
    company: 'Zoox',
    vehicle_make: 'Zoox',
    vehicle_model: 'Robotaxi',
    location_address: '1355 Market St, San Francisco, CA',
    location_lat: 37.7767,
    location_lng: -122.4142,
    city: 'San Francisco',
    county: 'San Francisco',
    city_type: 'urban',
    intersection_type: 'traffic light',
    damage_severity: 'minor',
    weather_conditions: 'fog',
    time_of_day: '15:15',
    casualties: 0,
    av_mode: 'autonomous',
    speed_limit: 35,
    traffic_signals: 'functioning',
    road_type: 'arterial',
    damage_location: 'rear',
    raw_text: 'Zoox robotaxi rear-end collision in fog',
    report_url: 'https://dmv.ca.gov/report/7',
    created_at: '2023-12-09T15:20:00Z'
  },
  {
    id: 8,
    timestamp: '2023-12-08T12:00:00Z',
    company: 'Apple',
    vehicle_make: 'Lexus',
    vehicle_model: 'RX450h',
    location_address: '1 Infinite Loop, Cupertino, CA',
    location_lat: 37.3318,
    location_lng: -122.0312,
    city: 'Cupertino',
    county: 'Santa Clara',
    city_type: 'suburban',
    intersection_type: 'roundabout',
    damage_severity: 'moderate',
    weather_conditions: 'clear',
    time_of_day: '12:00',
    casualties: 1,
    av_mode: 'autonomous',
    speed_limit: 25,
    traffic_signals: 'none',
    road_type: 'arterial',
    damage_location: 'front',
    raw_text: 'Apple test vehicle collision at roundabout',
    report_url: 'https://dmv.ca.gov/report/8',
    created_at: '2023-12-08T12:05:00Z'
  }
];

export const mockMapData = {
  accidents: mockAccidents,
  clusters: [],
  heatmap: [],
  bounds: {
    north: 38.0,
    south: 37.0,
    east: -121.0,
    west: -123.0
  }
};

export const mockAnalytics = {
  company_stats: [
    {
      company: "Waymo",
      accident_count: 49,
      severity_breakdown: { minor: 30, moderate: 15, severe: 4 },
      growth_rate: -8.2,
      market_share: 35.5,
      avg_casualties: 0.2
    },
    {
      company: "Cruise",
      accident_count: 41,
      severity_breakdown: { minor: 22, moderate: 14, severe: 5 },
      growth_rate: -15.1,
      market_share: 29.7,
      avg_casualties: 0.3
    },
    {
      company: "Tesla",
      accident_count: 23,
      severity_breakdown: { minor: 12, moderate: 8, severe: 3 },
      growth_rate: 5.3,
      market_share: 16.7,
      avg_casualties: 0.4
    },
    {
      company: "Zoox",
      accident_count: 15,
      severity_breakdown: { minor: 8, moderate: 5, severe: 2 },
      growth_rate: -3.7,
      market_share: 10.9,
      avg_casualties: 0.2
    },
    {
      company: "Apple",
      accident_count: 6,
      severity_breakdown: { minor: 3, moderate: 2, severe: 1 },
      growth_rate: -25.0,
      market_share: 4.3,
      avg_casualties: 0.5
    }
  ],
  summary: {
    total_accidents: 134,
    trend_direction: "decreasing",
    trend_percentage: -12.3,
    most_dangerous_hour: "17:00",
    safest_company: "Waymo",
    most_common_severity: "minor"
  }
};
